---
- name: Configuration tasks
  tags:
    - postfix_config
    - postfix
  become: true
  block:

    # === Load default config ===
    - name: Load default configs
      set_fact:
        postfix_main_config_parsed: "{{ postfix_main_config_default | from_yaml }}"
        postfix_master_config_parsed: "{{ postfix_master_config_default | from_yaml }}"

    # === Load vars config ===
    - name: Load vars configs
      set_fact:
        postfix_main_config_yaml: "{{ postfix_main_config_options | from_yaml }}"
        postfix_master_config_yaml: "{{ postfix_master_config_options | from_yaml }}"

    # === Merge main.cf variables ===
    - name: Merge main.cf variables
      set_fact:
        postfix_main_config_merged: >-
          {{
            postfix_main_config_parsed | ansible.builtin.combine(postfix_main_config_options, recursive=True)
          }}

    # === Merge master.cf variables ===
    - name: Combine master.cf configs
      set_fact:
        postfix_master_config_merged: "{{ postfix_master_config_parsed + postfix_master_config_yaml }}"

    # === Debug variables ===
    - name: Debug variables
      ansible.builtin.include_tasks: debug/config.yml
      when: postfix_debug | default(false)

    # === Create config files ===
    - name: Manage main.cf
      template:
        src: main.cf.j2
        dest: "{{ postfix_main_config_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart postfix
      when: postfix_main_config_merged | length > 0

    - name: Manage master.cf
      template:
        src: master.cf.j2
        dest: "{{ postfix_master_config_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Restart postfix
      when: postfix_master_config_merged | length > 0

    - name: Manage transport map
      template:
        src: transport.j2
        dest: "{{ postfix_transport_config_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Rebuild transport map

    - name: Manage access map
      template:
        src: access.j2
        dest: "{{ postfix_access_config_file }}"
        owner: root
        group: root
        mode: '0644'
      notify: Rebuild access map
