---

- name: Install tasks
  tags:
    - postfix_install
    - postfix
  become: true

  block:
    - name: Install postfix package
      ansible.builtin.yum:
        name: "{{ postfix_package_name }}"
        state: "{{ postfix_package_ensure }}"
        update_cache: true
      register: postfix_install
      when: ansible_os_family == "RedHat"

    - name: Install postfix package
      ansible.builtin.apt:
        name: "{{ postfix_package_name }}"
        state: "{{ postfix_package_ensure }}"
        update_cache: true
      register: postfix_install
      when: ansible_os_family == "Debian"
